name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on PRs targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.0.5'  # Set the Node.js version you're using

       # Step 3: Install dependencies
      - name: Install vercel CLI
        run: npm install --global vercel

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install
      
        # Step 5: Run Tests
      - name: Run Tests
        run: npm test

      # Setp 5 , use vercel  
      - name: Pull vercel environment information
        run: vercel pull --yes --environment=production --token=${{secrets.VERCEL_TOKEN}}

      # Step 6: Build Project artiface
      - name: Build Project artifact
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      # Step 6: deploy Project artiface
      - name: deploy Project artifact
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}

        env:
          DB_URL: ${{ secrets.DB_CONNECTION }}
